### ISSUE TITLE
How to use BLOC pattern to validate 'Confirm Password' text field?

### ISSUE THREAD

**Issue by jonahfang** [hoc081098/flutter_validation_login_form_BLoC_pattern_RxDart#1]
I am using a Stream/Observable to validate 'Password' text field like final _emailController = BehaviorSubject<String>(); Stream<String> get email => _emailController.stream.transform(validateEmail); where valdiateEmail is a StreamTransformer<String,String> to validate whether the password length is at least 6. I am trying to use the similar idea for 'Confirm Password' but the validate function would take two inputs: password, confirmPassword; not sure how to handle this using StreamTransformer.

**Comment by hoc081098** [comment]
sorry for late reply, you can use combineLatest operator, and compare password and confirm password

**Comment by jonahfang** [comment]
@hoc081098 Thank you very much, I will try.
